<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241116113022 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "books" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, shelf_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4A1B2A927C12FBC0 ON "books" (shelf_id)');
        $this->addSql('CREATE TABLE "profiles" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) DEFAULT NULL, surname VARCHAR(255) DEFAULT NULL, nickname VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8B308530A76ED395 ON "profiles" (user_id)');
        $this->addSql('CREATE TABLE "shelves" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE "users" 
                            (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                            email VARCHAR(128) NOT NULL, 
                            password VARCHAR(255) NOT NULL, 
                            email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, 
                            roles JSON NOT NULL, 
                            isActive BOOLEAN DEFAULT false NOT NULL, 
                            created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, 
                            updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, 
                            PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON "users" (email)');
        $this->addSql('ALTER TABLE "books" ADD CONSTRAINT FK_4A1B2A927C12FBC0 FOREIGN KEY (shelf_id) REFERENCES "shelves" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "profiles" ADD CONSTRAINT FK_8B308530A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE "books" DROP CONSTRAINT FK_4A1B2A927C12FBC0');
        $this->addSql('ALTER TABLE "profiles" DROP CONSTRAINT FK_8B308530A76ED395');
        $this->addSql('DROP TABLE "books"');
        $this->addSql('DROP TABLE "profiles"');
        $this->addSql('DROP TABLE "shelves"');
        $this->addSql('DROP TABLE "users"');
    }
}
