<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241110192711 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "profiles" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                            name VARCHAR(255) DEFAULT NULL, 
                            surname VARCHAR(255) DEFAULT NULL, 
                            nickname VARCHAR(255) DEFAULT NULL, 
                            phone VARCHAR(255) DEFAULT NULL, 
                            avatar VARCHAR(255) DEFAULT NULL, 
                            address VARCHAR(255) DEFAULT NULL, 
                            created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, 
                            updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, 
                            user_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8B308530A76ED395 ON "profiles" (user_id)');
        $this->addSql('CREATE TABLE "users" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
                                                email VARCHAR(128) NOT NULL, 
                                                password VARCHAR(255) NOT NULL, 
                                                email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, 
                                                created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, 
                                                updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, 
                                                PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON "users" (email)');
        $this->addSql('ALTER TABLE "profiles" ADD CONSTRAINT FK_8B308530A76ED395 FOREIGN KEY (user_id) REFERENCES "users" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE "profiles" DROP CONSTRAINT FK_8B308530A76ED395');
        $this->addSql('DROP TABLE "profiles"');
        $this->addSql('DROP TABLE "users"');
    }
}
